version: "3.9"

services:
  db:
    image: postgres:15
    container_name: wasteworth-db
    restart: always
    environment:
      POSTGRES_USER: avnadmin
      POSTGRES_PASSWORD: localpass
      POSTGRES_DB: wasteworth_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U avnadmin -d wasteworth_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Django app service that auto-migrates
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_HOST=db

volumes:
  db_data:
