# Generated by Django 5.2.6 on 2025-10-08 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_phone'),
        ('marketplace', '0003_alter_marketplacelisting_recycler_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='auto_confirm_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='disposer_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='item_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='payment_initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='payment_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='recycler_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='escrow_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_initiated', 'Payment Initiated'), ('locked', 'Locked'), ('item_released', 'Item Released'), ('confirmed', 'Confirmed'), ('released', 'Released'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='marketplacelisting',
            index=models.Index(fields=['escrow_status', '-created_at'], name='mp_escrow_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacelisting',
            index=models.Index(fields=['auto_confirm_deadline'], name='mp_deadline_idx'),
        ),
    ]
