# Generated by Django 5.2.6 on 2025-10-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_marketplacelisting_auto_confirm_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='marketplacelisting',
            name='mp_deadline_idx',
        ),
        migrations.RemoveField(
            model_name='marketplacelisting',
            name='auto_confirm_deadline',
        ),
    ]
