# Generated by Django 5.2.6 on 2025-09-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='referee_id',
            new_name='referee',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='referrer_id',
            new_name='referrer',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='bonus_amount',
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_reward',
            field=models.IntegerField(default=0),
        ),
    ]
