# Generated by Django 5.2.6 on 2025-10-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="User's first name", max_length=100)),
                ('last_name', models.CharField(blank=True, help_text="User's last name (optional)", max_length=100)),
                ('email', models.EmailField(help_text="User's email address", max_length=254)),
                ('message', models.TextField(help_text="User's message or inquiry")),
                ('heard_about', models.CharField(blank=True, help_text='How the user heard about WasteWorth (e.g., Instagram, Facebook, Friend)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
