# Generated by Django 5.2.6 on 2025-10-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='paystack_transfer_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='paystack_transfer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
