# Generated by Django 5.2.6 on 2025-09-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='temp@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('disposer', 'Disposer'), ('recycler', 'Recycler'), ('admin', 'Admin')], default='disposer', max_length=20),
        ),
    ]
