# Generated by Django 5.2.6 on 2025-09-20 12:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waste_type', models.CharField(choices=[('plastic', 'Plastic'), ('glass', 'Glass'), ('paper', 'Paper')], default='plastic', max_length=20)),
                ('quantity', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reward_estimate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_reward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pickup_location', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'listings',
            },
        ),
    ]
