# Generated by Django 5.2.6 on 2025-09-20 13:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listingId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wasteType', models.CharField(choices=[('plastic', 'Plastic'), ('glass', 'Glass'), ('paper', 'Paper')], default='plastic', max_length=20)),
                ('quantity', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('rewardEstimate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finalReward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pickupLocation', models.JSONField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('collectorId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_listings', to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('marketplaceId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wasteType', models.CharField(choices=[('plastic', 'Plastic'), ('glass', 'Glass'), ('paper', 'Paper')], max_length=20)),
                ('quantityKg', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('escrowStatus', models.CharField(choices=[('pending', 'Pending'), ('locked', 'Locked'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('pickupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to='listings.listing')),
                ('recyclerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
