# Generated by Django 5.2.6 on 2025-10-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_image_url_listing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
