# Generated by Django 5.2.6 on 2025-10-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
