# Generated by Django 5.2.6 on 2025-09-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='wallet',
            name='points',
            field=models.IntegerField(default=0, help_text='Eco-points earned via referrals and recycling activity'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cash balance (Naira, Cedis, etc.)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank'), ('mobileMoney', 'Mobile Money'), ('airtime', 'Airtime'), ('voucher', 'Voucher'), ('system', 'System Credit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('payout', 'Payout'), ('referral_reward', 'Referral Reward'), ('activity_reward', 'Activity Reward'), ('redeem', 'Redeem Points')], max_length=20),
        ),
    ]
