# Generated by Django 5.2.6 on 2025-09-26 19:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_user_id_wallet_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='NGN', help_text='Currency code (NGN, GHS, etc.)', max_length=3),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional transaction data', null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reference',
            field=models.CharField(blank=True, help_text='External reference number', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in currency', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('mobileMoney', 'Mobile Money'), ('airtime', 'Airtime'), ('voucher', 'Voucher'), ('system', 'System Credit'), ('card', 'Card Payment'), ('paypal', 'PayPal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='points',
            field=models.IntegerField(blank=True, help_text='Points involved in transaction', null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('payout', 'Payout'), ('referral_reward', 'Referral Reward'), ('activity_reward', 'Activity Reward'), ('redeem', 'Redeem Points'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund')], max_length=20),
        ),
    ]
