# Generated by Django 5.2.6 on 2025-10-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_add_wallet_transaction_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('mobileMoney', 'Mobile Money'), ('airtime', 'Airtime'), ('voucher', 'Voucher'), ('system', 'System Credit'), ('card', 'Card Payment'), ('referral_reward', 'Referral Reward'), ('activity_reward', 'Activity Reward'), ('redeem', 'Redeem Points')], max_length=20),
        ),
    ]
